{"nodes":[

{"name": "Administración", "group": 1},
{"name": "Contaduría Int.", "group": 1},
{"name": "Arquitectura", "group": 2},
{"name": "Diseño", "group": 2},
{"name": "Arte", "group": 3},
{"name": "Historia del Arte", "group": 3},
{"name": "Literatura", "group": 3},
{"name": "Música", "group": 3},
{"name": "Biología", "group": 4},
{"name": "Física", "group": 4},
{"name": "Geociencias", "group": 4},
{"name": "Matemáticas", "group": 4},
{"name": "Microbiología", "group": 4},
{"name": "Química", "group": 4},
{"name": "Antropología", "group": 5},
{"name": "Ciencia Política", "group": 5},
{"name": "Filosofía", "group": 5},
{"name": "Historia", "group": 5},
{"name": "Lenguas (LyES + LyC)", "group": 5},
{"name": "Psicología", "group": 5},
{"name": "Derecho", "group": 6},
{"name": "Economía", "group": 7},
{"name": "Gobierno y A. Públicos", "group": 8},
{"name": "Ing. Ambiental", "group": 9},
{"name": "Ing. Biomédica", "group": 9},
{"name": "Ing. Civil", "group": 9},
{"name": "Ing. Eléctrica", "group": 9},
{"name": "Ing. Electrónica", "group": 9},
{"name": "Ing. Industrial", "group": 9},
{"name": "Ing. Mecánica", "group": 9},
{"name": "Ing. Química", "group": 9},
{"name": "Ing. de Sistemas", "group": 9},
{"name": "Medicina", "group": 10},
{"name": "Lic. Ciencias Sociales", "group": 11},
{"name": "Lic. en Matemáticas", "group": 11} 


],"links":[

{"source": "21", "target": "0", "value": 21},
{"source": "28", "target": "21", "value": 13},
{"source": "28", "target": "0", "value": 13},
{"source": "3", "target": "2", "value": 10},
{"source": "20", "target": "15", "value": 10},
{"source": "25", "target": "23", "value": 9},
{"source": "31", "target": "28", "value": 9},
{"source": "25", "target": "2", "value": 8},
{"source": "12", "target": "8", "value": 7},
{"source": "4", "target": "3", "value": 7},
{"source": "22", "target": "21", "value": 7},
{"source": "21", "target": "20", "value": 7},
{"source": "30", "target": "23", "value": 6},
{"source": "3", "target": "0", "value": 6},
{"source": "30", "target": "28", "value": 6},
{"source": "19", "target": "0", "value": 6},
{"source": "29", "target": "28", "value": 6},
{"source": "21", "target": "15", "value": 5},
{"source": "20", "target": "0", "value": 5},
{"source": "28", "target": "25", "value": 5},
{"source": "4", "target": "2", "value": 5},
{"source": "25", "target": "10", "value": 4},
{"source": "29", "target": "27", "value": 4},
{"source": "31", "target": "27", "value": 4},
{"source": "27", "target": "26", "value": 4},
{"source": "2", "target": "0", "value": 3},
{"source": "22", "target": "20", "value": 3},
{"source": "29", "target": "9", "value": 3},
{"source": "22", "target": "15", "value": 3},
{"source": "28", "target": "23", "value": 3},
{"source": "20", "target": "16", "value": 3},
{"source": "30", "target": "24", "value": 3},
{"source": "28", "target": "3", "value": 3},
{"source": "29", "target": "3", "value": 3},
{"source": "5", "target": "4", "value": 3},
{"source": "1", "target": "0", "value": 3},
{"source": "25", "target": "0", "value": 3},
{"source": "11", "target": "9", "value": 3},
{"source": "24", "target": "12", "value": 3},
{"source": "30", "target": "13", "value": 3},
{"source": "29", "target": "25", "value": 3},
{"source": "31", "target": "3", "value": 3},
{"source": "10", "target": "9", "value": 3},
{"source": "15", "target": "14", "value": 3},
{"source": "20", "target": "17", "value": 2},
{"source": "20", "target": "19", "value": 2},
{"source": "32", "target": "24", "value": 2},
{"source": "18", "target": "15", "value": 2},
{"source": "19", "target": "3", "value": 2},
{"source": "30", "target": "12", "value": 2},
{"source": "20", "target": "14", "value": 2},
{"source": "29", "target": "24", "value": 2},
{"source": "23", "target": "10", "value": 2},
{"source": "21", "target": "11", "value": 2},
{"source": "32", "target": "12", "value": 2},
{"source": "19", "target": "14", "value": 2},
{"source": "30", "target": "0", "value": 2},
{"source": "14", "target": "4", "value": 2},
{"source": "23", "target": "8", "value": 2},
{"source": "27", "target": "24", "value": 2},
{"source": "28", "target": "27", "value": 2},
{"source": "29", "target": "0", "value": 2},
{"source": "17", "target": "14", "value": 2},
{"source": "28", "target": "24", "value": 2},
{"source": "15", "target": "0", "value": 2},
{"source": "7", "target": "0", "value": 2},
{"source": "5", "target": "2", "value": 2},
{"source": "16", "target": "6", "value": 2},
{"source": "19", "target": "6", "value": 2},
{"source": "19", "target": "15", "value": 2},
{"source": "22", "target": "0", "value": 2},
{"source": "18", "target": "6", "value": 2},
{"source": "20", "target": "6", "value": 2},
{"source": "24", "target": "8", "value": 2},
{"source": "30", "target": "8", "value": 2},
{"source": "31", "target": "11", "value": 2},
{"source": "21", "target": "16", "value": 2},
{"source": "28", "target": "19", "value": 2},
{"source": "27", "target": "9", "value": 1},
{"source": "17", "target": "15", "value": 1},
{"source": "19", "target": "18", "value": 1},
{"source": "31", "target": "24", "value": 1},
{"source": "30", "target": "29", "value": 1},
{"source": "31", "target": "0", "value": 1},
{"source": "10", "target": "8", "value": 1},
{"source": "21", "target": "14", "value": 1},
{"source": "25", "target": "21", "value": 1},
{"source": "18", "target": "0", "value": 1},
{"source": "23", "target": "0", "value": 1},
{"source": "6", "target": "4", "value": 1},
{"source": "28", "target": "11", "value": 1},
{"source": "13", "target": "12", "value": 1},
{"source": "32", "target": "19", "value": 1},
{"source": "31", "target": "29", "value": 1},
{"source": "5", "target": "3", "value": 1},
{"source": "14", "target": "3", "value": 1},
{"source": "19", "target": "4", "value": 1},
{"source": "14", "target": "8", "value": 1},
{"source": "32", "target": "8", "value": 1},
{"source": "14", "target": "2", "value": 1},
{"source": "6", "target": "5", "value": 1},
{"source": "19", "target": "7", "value": 1},
{"source": "30", "target": "9", "value": 1},
{"source": "16", "target": "15", "value": 1},
{"source": "19", "target": "16", "value": 1},
{"source": "21", "target": "17", "value": 1},
{"source": "28", "target": "22", "value": 1},
{"source": "23", "target": "2", "value": 1},
{"source": "17", "target": "6", "value": 1},
{"source": "21", "target": "7", "value": 1},
{"source": "19", "target": "8", "value": 1},
{"source": "13", "target": "9", "value": 1},
{"source": "24", "target": "9", "value": 1},
{"source": "31", "target": "9", "value": 1},
{"source": "30", "target": "10", "value": 1},
{"source": "27", "target": "11", "value": 1},
{"source": "23", "target": "12", "value": 1},
{"source": "18", "target": "14", "value": 1},
{"source": "28", "target": "20", "value": 1},
{"source": "24", "target": "0", "value": 1},
{"source": "20", "target": "3", "value": 1},
{"source": "23", "target": "3", "value": 1},
{"source": "24", "target": "3", "value": 1},
{"source": "30", "target": "3", "value": 1},
{"source": "7", "target": "4", "value": 1},
{"source": "8", "target": "4", "value": 1},
{"source": "18", "target": "4", "value": 1},
{"source": "25", "target": "9", "value": 1},
{"source": "25", "target": "11", "value": 1},
{"source": "24", "target": "13", "value": 1},
{"source": "31", "target": "25", "value": 1},
{"source": "4", "target": "0", "value": 1},
{"source": "20", "target": "1", "value": 1},
{"source": "28", "target": "2", "value": 1},
{"source": "29", "target": "2", "value": 1},
{"source": "6", "target": "3", "value": 1},
{"source": "7", "target": "3", "value": 1},
{"source": "15", "target": "3", "value": 1},
{"source": "27", "target": "3", "value": 1},
{"source": "15", "target": "4", "value": 1},
{"source": "21", "target": "4", "value": 1},
{"source": "20", "target": "7", "value": 1},
{"source": "31", "target": "7", "value": 1},
{"source": "9", "target": "8", "value": 1},
{"source": "16", "target": "9", "value": 1},
{"source": "21", "target": "9", "value": 1},
{"source": "28", "target": "9", "value": 1},
{"source": "29", "target": "10", "value": 1},
{"source": "16", "target": "14", "value": 1},
{"source": "17", "target": "16", "value": 1},
{"source": "20", "target": "18", "value": 1},
{"source": "21", "target": "19", "value": 1},
{"source": "22", "target": "19", "value": 1},
{"source": "24", "target": "19", "value": 1},
{"source": "5", "target": "0", "value": 1},
{"source": "6", "target": "0", "value": 1},
{"source": "14", "target": "0", "value": 1},
{"source": "16", "target": "4", "value": 1},
{"source": "20", "target": "4", "value": 1},
{"source": "21", "target": "5", "value": 1},
{"source": "14", "target": "6", "value": 1},
{"source": "15", "target": "6", "value": 1},
{"source": "21", "target": "6", "value": 1},
{"source": "28", "target": "7", "value": 1},
{"source": "28", "target": "10", "value": 1},
{"source": "29", "target": "11", "value": 1},
{"source": "23", "target": "15", "value": 1},
{"source": "30", "target": "19", "value": 1},
{"source": "25", "target": "20", "value": 1},
{"source": "29", "target": "21", "value": 1},
{"source": "29", "target": "26", "value": 1},
{"source": "31", "target": "30", "value": 1},
{"source": "12", "target": "0", "value": 1},
{"source": "17", "target": "0", "value": 1},
{"source": "27", "target": "0", "value": 1},
{"source": "28", "target": "1", "value": 1},
{"source": "7", "target": "2", "value": 1},
{"source": "9", "target": "2", "value": 1},
{"source": "20", "target": "2", "value": 1},
{"source": "21", "target": "2", "value": 1},
{"source": "25", "target": "3", "value": 1},
{"source": "18", "target": "7", "value": 1},
{"source": "25", "target": "7", "value": 1},
{"source": "27", "target": "7", "value": 1},
{"source": "13", "target": "8", "value": 1},
{"source": "26", "target": "9", "value": 1},
{"source": "24", "target": "11", "value": 1},
{"source": "19", "target": "12", "value": 1},
{"source": "32", "target": "13", "value": 1},
{"source": "23", "target": "14", "value": 1},
{"source": "18", "target": "17", "value": 1},
{"source": "21", "target": "18", "value": 1},
{"source": "22", "target": "18", "value": 1},
{"source": "28", "target": "18", "value": 1},
{"source": "23", "target": "19", "value": 1},
{"source": "31", "target": "21", "value": 1},
{"source": "29", "target": "23", "value": 1},
{"source": "26", "target": "25", "value": 1},
{"source": "27", "target": "25", "value": 1},
{"source": "28", "target": "26", "value": 1},
{"source": "31", "target": "26", "value": 1},
{"source": "32", "target": "28", "value": 1},
{"source": "10", "target": "0", "value": 1},
{"source": "13", "target": "0", "value": 1},
{"source": "16", "target": "0", "value": 1},
{"source": "32", "target": "0", "value": 1},
{"source": "18", "target": "2", "value": 1},
{"source": "19", "target": "2", "value": 1},
{"source": "27", "target": "2", "value": 1},
{"source": "16", "target": "3", "value": 1},
{"source": "17", "target": "3", "value": 1},
{"source": "18", "target": "3", "value": 1},
{"source": "21", "target": "3", "value": 1},
{"source": "32", "target": "3", "value": 1},
{"source": "9", "target": "4", "value": 1},
{"source": "17", "target": "4", "value": 1},
{"source": "25", "target": "4", "value": 1},
{"source": "7", "target": "5", "value": 1},
{"source": "14", "target": "5", "value": 1},
{"source": "9", "target": "6", "value": 1},
{"source": "22", "target": "6", "value": 1},
{"source": "9", "target": "7", "value": 1},
{"source": "15", "target": "7", "value": 1},
{"source": "22", "target": "7", "value": 1},
{"source": "11", "target": "8", "value": 1},
{"source": "16", "target": "8", "value": 1},
{"source": "20", "target": "8", "value": 1},
{"source": "31", "target": "8", "value": 1},
{"source": "14", "target": "9", "value": 1},
{"source": "14", "target": "10", "value": 1},
{"source": "19", "target": "10", "value": 1},
{"source": "31", "target": "10", "value": 1},
{"source": "16", "target": "11", "value": 1},
{"source": "23", "target": "13", "value": 1},
{"source": "28", "target": "13", "value": 1},
{"source": "22", "target": "14", "value": 1},
{"source": "24", "target": "14", "value": 1},
{"source": "28", "target": "14", "value": 1},
{"source": "18", "target": "16", "value": 1},
{"source": "29", "target": "18", "value": 1},
{"source": "27", "target": "19", "value": 1},
{"source": "23", "target": "20", "value": 1},
{"source": "30", "target": "20", "value": 1},
{"source": "32", "target": "20", "value": 1},
{"source": "23", "target": "21", "value": 1},
{"source": "27", "target": "21", "value": 1},
{"source": "30", "target": "21", "value": 1},
{"source": "23", "target": "22", "value": 1},
{"source": "32", "target": "30", "value": 1},
{"source": "8", "target": "0", "value": 1},
{"source": "11", "target": "0", "value": 1},
{"source": "14", "target": "1", "value": 1},
{"source": "15", "target": "1", "value": 1},
{"source": "18", "target": "1", "value": 1},
{"source": "21", "target": "1", "value": 1},
{"source": "22", "target": "1", "value": 1},
{"source": "30", "target": "1", "value": 1},
{"source": "6", "target": "2", "value": 1},
{"source": "10", "target": "2", "value": 1},
{"source": "11", "target": "2", "value": 1},
{"source": "15", "target": "2", "value": 1},
{"source": "16", "target": "2", "value": 1},
{"source": "17", "target": "2", "value": 1},
{"source": "22", "target": "2", "value": 1},
{"source": "32", "target": "2", "value": 1},
{"source": "12", "target": "3", "value": 1},
{"source": "13", "target": "3", "value": 1},
{"source": "22", "target": "3", "value": 1},
{"source": "22", "target": "4", "value": 1},
{"source": "24", "target": "4", "value": 1},
{"source": "30", "target": "4", "value": 1},
{"source": "32", "target": "4", "value": 1},
{"source": "8", "target": "5", "value": 1},
{"source": "16", "target": "5", "value": 1},
{"source": "17", "target": "5", "value": 1},
{"source": "18", "target": "5", "value": 1},
{"source": "19", "target": "5", "value": 1},
{"source": "20", "target": "5", "value": 1},
{"source": "22", "target": "5", "value": 1},
{"source": "32", "target": "5", "value": 1},
{"source": "7", "target": "6", "value": 1},
{"source": "11", "target": "6", "value": 1},
{"source": "30", "target": "6", "value": 1},
{"source": "31", "target": "6", "value": 1},
{"source": "32", "target": "6", "value": 1},
{"source": "8", "target": "7", "value": 1},
{"source": "10", "target": "7", "value": 1},
{"source": "11", "target": "7", "value": 1},
{"source": "13", "target": "7", "value": 1},
{"source": "23", "target": "7", "value": 1},
{"source": "24", "target": "7", "value": 1},
{"source": "30", "target": "7", "value": 1},
{"source": "32", "target": "7", "value": 1},
{"source": "25", "target": "8", "value": 1},
{"source": "18", "target": "9", "value": 1},
{"source": "23", "target": "9", "value": 1},
{"source": "32", "target": "9", "value": 1},
{"source": "12", "target": "10", "value": 1},
{"source": "13", "target": "10", "value": 1},
{"source": "18", "target": "10", "value": 1},
{"source": "20", "target": "10", "value": 1},
{"source": "22", "target": "10", "value": 1},
{"source": "27", "target": "10", "value": 1},
{"source": "13", "target": "11", "value": 1},
{"source": "19", "target": "11", "value": 1},
{"source": "26", "target": "11", "value": 1},
{"source": "34", "target": "11", "value": 1},
{"source": "14", "target": "12", "value": 1},
{"source": "28", "target": "12", "value": 1},
{"source": "31", "target": "12", "value": 1},
{"source": "16", "target": "13", "value": 1},
{"source": "25", "target": "13", "value": 1},
{"source": "26", "target": "13", "value": 1},
{"source": "32", "target": "14", "value": 1},
{"source": "28", "target": "15", "value": 1},
{"source": "30", "target": "15", "value": 1},
{"source": "28", "target": "16", "value": 1},
{"source": "29", "target": "16", "value": 1},
{"source": "31", "target": "16", "value": 1},
{"source": "19", "target": "17", "value": 1},
{"source": "23", "target": "17", "value": 1},
{"source": "28", "target": "17", "value": 1},
{"source": "31", "target": "17", "value": 1},
{"source": "24", "target": "18", "value": 1},
{"source": "25", "target": "18", "value": 1},
{"source": "31", "target": "18", "value": 1},
{"source": "32", "target": "18", "value": 1},
{"source": "33", "target": "19", "value": 1},
{"source": "29", "target": "20", "value": 1},
{"source": "31", "target": "20", "value": 1},
{"source": "24", "target": "21", "value": 1},
{"source": "26", "target": "21", "value": 1},
{"source": "32", "target": "21", "value": 1},
{"source": "24", "target": "22", "value": 1},
{"source": "25", "target": "22", "value": 1},
{"source": "31", "target": "22", "value": 1},
{"source": "32", "target": "22", "value": 1},
{"source": "24", "target": "23", "value": 1},
{"source": "31", "target": "23", "value": 1},
{"source": "25", "target": "24", "value": 1},
{"source": "26", "target": "24", "value": 1},
{"source": "30", "target": "25", "value": 1},
{"source": "30", "target": "26", "value": 1},
{"source": "34", "target": "26", "value": 1},
{"source": "30", "target": "27", "value": 1},
{"source": "32", "target": "31", "value": 1}

]}
